platform :ios, '8.0’

target ‘LHBD’ do

 pod 'Reachability', '~> 3.2'
#pod 'MyUUID'
#pod 'SSZipArchive'
#pod 'YYCache'
pod 'JKCategories'
pod 'JPush'
pod 'MJRefresh'
pod 'Masonry', '~> 1.0.1'
 pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SVProgressHUD'
#pod 'SDCycleScrollView'
pod 'SDWebImage'
pod 'DZNEmptyDataSet'
end
